name: Check Status
on:
  status
jobs:
  if_success:
    runs-on: ubuntu-latest
    # if: >-
    #   github.event.state == 'success'
    steps:
      - env:
          DESCRIPTION: ${{ github.event.description }}
          NAME: ${{ github.event.name}}
          STATE: ${{ github.event.state }}
        run: |
          echo DESCRIPTION: $DESCRIPTION          
          echo NAME: $NAME
          echo STATE: $STATE