name: Check Run
on:
  check_run:
    types: [completed]
jobs:
  build:
    name: Check Run Workflow
    runs-on: ubuntu-latest
    steps:
      - env:
          URL: ${{ github.event.check_run.html_url }}          
          CHECK_SUITE: ${{ github.event.check_run.check_suite  }}
          CONCLUSION: ${{ github.event.check_run.conclusion }}
          SHA: ${{ github.event.check_run.head_sha }}
          STATUS: ${{ github.event.check_run.status }}
        run: |
          echo URL: $URL          
          echo CHECK_SUITE: $CHECK_SUITE          
          echo SHA: $SHA
          echo CONCLUSION: $CONCLUSION
          echo STATUS: $STATUS
