name: CodeBuild
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: codebuild-test-with-github-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: envv
        run: env
